VERSION = "1.2"
APP_DEFAULT_WIDTH = 1000
APP_DEFAULT_HEIGHT = 800
TOP_BAR_HEIGHT = 250
MAX_CHANNELS = 8


SETTINGS_BIN_WIDTH = "bin_width"
DEFAULT_BIN_WIDTH = 1000
SETTINGS_TIME_SPAN = "time_span"
DEFAULT_TIME_SPAN = 10
SETTINGS_CONNECTION_TYPE = "connection_type"
SETTINGS_CALIBRATION_TYPE = "calibration"
DEFAULT_SETTINGS_CALIBRATION_TYPE = 0
DEFAULT_CONNECTION_TYPE = "1"
SETTINGS_FREE_RUNNING = "free_running"
DEFAULT_FREE_RUNNING = "false"
SETTINGS_ACQUISITION_TIME = "acquisition_time"
SETTINGS_TAU_NS = "tau_ns"
SETTINGS_HARMONIC = "harmonic"
HARMONIC_SELECTOR = "harmonic_selector"
HARMONIC_SELECTOR_LABEL = "harmonic_selector_label"
SETTINGS_HARMONIC_LABEL = "harmonic_label"
SETTINGS_HARMONIC_DEFAULT = 1
DEFAULT_ACQUISITION_TIME = 10
SETTINGS_SYNC = "sync"
DEFAULT_SYNC = "sync_in"
SETTINGS_SYNC_IN_FREQUENCY_MHZ = "sync_in_frequency_mhz"
DEFAULT_SYNC_IN_FREQUENCY_MHZ = 0.0
SETTINGS_WRITE_DATA = "write_data"
DEFAULT_WRITE_DATA = True
CURSOR_TEXT = "⨁"

LOAD_REF_BTN = "load_reference_btn"

MODE_STOPPED = "stopped"
MODE_RUNNING = "running"

PALETTE_RED_1 = "#DA1212"
PALETTE_BLUE_1 = "#11468F"

TOP_COLLAPSIBLE_WIDGET = "top_collapsible_widget"
PLOTS_CONFIG_POPUP = "plots_config_popup"

SETTINGS_PLOTS_TO_SHOW = "plots_to_show"
DEFAULT_PLOTS_TO_SHOW = "[]"

CHANNELS_GRID = "channels_grid"

DOWNLOAD_BUTTON = "download_button"
DOWNLOAD_MENU = "download_menu"

SPECTROSCOPY_SCRIPT_ACTION = "spectroscopy_script_action"
PHASORS_SCRIPT_ACTION = "phasors_script_action"
