VERSION = "1.0"
APP_DEFAULT_WIDTH = 1000
APP_DEFAULT_HEIGHT = 800
TOP_BAR_HEIGHT = 210
MAX_CHANNELS = 8

SETTINGS_BIN_WIDTH = "bin_width"
DEFAULT_BIN_WIDTH = 1000

SETTINGS_TIME_SPAN = "time_span"
DEFAULT_TIME_SPAN = 10

SETTINGS_CONNECTION_TYPE = "connection_type"
DEFAULT_CONNECTION_TYPE = "SMA"

SETTINGS_FREE_RUNNING = "free_running"
DEFAULT_FREE_RUNNING = "false"

SETTINGS_ACQUISITION_TIME = "acquisition_time"
DEFAULT_ACQUISITION_TIME = 10

SETTINGS_SYNC = "sync"
DEFAULT_SYNC = "sync_in"

SETTINGS_SYNC_IN_FREQUENCY_MHZ = "sync_in_frequency_mhz"
DEFAULT_SYNC_IN_FREQUENCY_MHZ = 0.0

SETTINGS_WRITE_DATA = "write_data"
DEFAULT_WRITE_DATA = True

SETTINGS_SHOW_CPS = "show_cps"
DEFAULT_SHOW_CPS = True

SETTINGS_SHOW_SNR = "show_snr"
DEFAULT_SHOW_SNR = True

MODE_STOPPED = "stopped"
MODE_RUNNING = "running"


EXPORTED_DATA_BYTES_UNIT = 12083.2