import json

SETTINGS_LASER_TYPE = "laser_type"
DEFAULT_LASER_TYPE = None
SETTINGS_FILTER_TYPE = "filter_type"
DEFAULT_FILTER_TYPE = None


FILTERS_TYPES_NARROW = [
    "400/16 nm",
    "420/16 nm",
    "440/16 nm",
    "460/15 nm",
    "480/15 nm",
    "500/15 nm",
    "520/15 nm",
    "540/15 nm",
    "560/14 nm",
    "580/14 nm",
    "600/14 nm",
    "620/14 nm",
    "640/14 nm",
    "660/13 nm",
    "680/13 nm",
    "700/13 nm",
    "720/13 nm",
    "740/13 nm",
    "765/22 nm",
    "795/22 nm",
]


FILTERS_TYPES_BROAD = [
    "450/50 ET Bandpass",
    "451/106 BrightLine HC",
    "550/100 ET Bandpass",
    "650/100 ET Bandpass",
    "775/140 BrightLine HC",
]

FILTERS_TYPES_NO_BANDPASS = ["SP", "LP"]


LASER_TYPES = [
    {
        "KEY": "375/10 nm",
        "LABEL": "Laser Clean-up Filter ZET 375/10",
        "BANDPASS": True,
        "FILTERS_NARROW": FILTERS_TYPES_NARROW,
        "FILTERS_BROAD": FILTERS_TYPES_BROAD[1:],
    },
    {
        "KEY": "405/10 nm",
        "LABEL": "405/10 ET Bandpass",
        "BANDPASS": True,
        "FILTERS_NARROW": FILTERS_TYPES_NARROW[2:],
        "FILTERS_BROAD": [
            FILTERS_TYPES_BROAD[0],
            FILTERS_TYPES_BROAD[2],
            FILTERS_TYPES_BROAD[3],
            FILTERS_TYPES_BROAD[4],
        ],
    },
    {
        "KEY": "445/10 nm",
        "LABEL": "Laser Clean-up Filter ZET 445/10",
        "BANDPASS": True,
        "FILTERS_NARROW": FILTERS_TYPES_NARROW[4:],
        "FILTERS_BROAD": [
            FILTERS_TYPES_BROAD[2],
            FILTERS_TYPES_BROAD[3],
            FILTERS_TYPES_BROAD[4],
        ],
    },
    {
        "KEY": "488/10 nm",
        "LABEL": " Laser Clean-up Filter ZET 488/10",
        "BANDPASS": True,
        "FILTERS_NARROW": FILTERS_TYPES_NARROW[6:],
        "FILTERS_BROAD": [
            FILTERS_TYPES_BROAD[2],
            FILTERS_TYPES_BROAD[3],
            FILTERS_TYPES_BROAD[4],
        ],
    },
    {
        "KEY": "520/10 nm",
        "LABEL": " 520/10 ET Bandpass",
        "BANDPASS": True,
        "FILTERS_NARROW": FILTERS_TYPES_NARROW[8:],
        "FILTERS_BROAD": FILTERS_TYPES_BROAD[3:],
    },
    {
        "KEY": "375 nm",
        "LABEL": "375 nm",
        "BANDPASS": False,
        "FILTERS_NARROW": FILTERS_TYPES_NARROW,
        "FILTERS_BROAD": FILTERS_TYPES_BROAD[1:],
    },
    {
        "KEY": "405 nm",
        "LABEL": "405 nm",
        "BANDPASS": False,
        "FILTERS_NARROW": FILTERS_TYPES_NARROW[2:],
        "FILTERS_BROAD": [
            FILTERS_TYPES_BROAD[0],
            FILTERS_TYPES_BROAD[2],
            FILTERS_TYPES_BROAD[3],
            FILTERS_TYPES_BROAD[4],
        ],
    },
    {
        "KEY": "445 nm",
        "LABEL": "445 nm",
        "BANDPASS": False,
        "FILTERS_NARROW": FILTERS_TYPES_NARROW[4:],
        "FILTERS_BROAD": [
            FILTERS_TYPES_BROAD[2],
            FILTERS_TYPES_BROAD[3],
            FILTERS_TYPES_BROAD[4],
        ],
    },
    {
        "KEY": "488 nm",
        "LABEL": "488 nm",
        "BANDPASS": False,
        "FILTERS_NARROW": FILTERS_TYPES_NARROW[6:],
        "FILTERS_BROAD": [
            FILTERS_TYPES_BROAD[2],
            FILTERS_TYPES_BROAD[3],
            FILTERS_TYPES_BROAD[4],
        ],
    },
    {
        "KEY": "520 nm",
        "LABEL": " 520 nm",
        "BANDPASS": False,
        "FILTERS_NARROW": FILTERS_TYPES_NARROW[8:],
        "FILTERS_BROAD": FILTERS_TYPES_BROAD[3:],
    },
]


ID = {
    "LABEL": "ID",
    "ID": "id",
    "UNIT": None,
    "VALUE": "",
    "INPUT_TYPE": "text",
    "OPTIONS": [],
    "MIN": None,
    "MAX": None,
    "POSITION": (0, 0, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}


PDAC_HEALTHY = {
    "LABEL": "PDAC/Healthy",
    "ID": "pdac_healthy",
    "UNIT": None,
    "OPTIONS": ["", "PDAC", "Healthy"],
    "VALUE": 0,
    "INPUT_TYPE": "select",
    "MIN": None,
    "MAX": None,
    "POSITION": (0, 1, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": False,
}

WEEKS = {
    "LABEL": "Weeks",
    "UNIT": None,
    "ID": "weeks",
    "VALUE": "",
    "INPUT_TYPE": "text",
    "OPTIONS": [],
    "MIN": None,
    "MAX": None,
    "POSITION": (0, 2, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": False,
}

SETTINGS_SAMPLE_VOL = {
    "LABEL": "Sample volume after incubation",
    "ID": "sample_vol",
    "UNIT": "µL",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (0, 3, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}

CUVETTE_TOTAL_VOL = {
    "LABEL": "Cuvette total volume",
    "UNIT": "µL",
    "ID": "cuvette_total_vol",
    "VALUE": 0,
    "OPTIONS": [],
    "INPUT_TYPE": "float",
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (1, 0, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
SOLVENT_TYPE = {
    "LABEL": "Solvent type",
    "ID": "solvent_type",
    "UNIT": None,
    "VALUE": "",
    "OPTIONS": [],
    "INPUT_TYPE": "text",
    "MIN": None,
    "MAX": None,
    "POSITION": (1, 1, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
SOLVENT_VOL = {
    "LABEL": "Solvent volume",
    "ID": "solvent_vol",
    "UNIT": "µL",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "MIN": 0,
    "OPTIONS": [],
    "MAX": 10000000,
    "POSITION": (1, 2, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
NANOPARTICLE_TYPE = {
    "LABEL": "Nanoparticle type",
    "ID": "nanoparticle_type",
    "UNIT": None,
    "VALUE": "",
    "OPTIONS": [],
    "INPUT_TYPE": "text",
    "MIN": None,
    "MAX": None,
    "POSITION": (1, 3, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
NANOPARTICLE_CONCENTRATION = {
    "LABEL": "Nanoparticle concentration",
    "ID": "nanoparticle_concentration",
    "UNIT": "µg/ µL",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (2, 0, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
NANOPARTICLE_VOL = {
    "LABEL": "Nanoparticle volume",
    "ID": "nanoparticle_vol",
    "UNIT": "ml",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (2, 1, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}

PROTEIN_SOURCE = {
    "LABEL": "Protein source",
    "ID": "protein_source",
    "UNIT": None,
    "OPTIONS": ["", "Human plasma", "Murine plasma"],
    "VALUE": 0,
    "INPUT_TYPE": "select",
    "MIN": None,
    "MAX": None,
    "POSITION": (2, 2, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": False,
}
PROTEIN_SOURCE_VOL = {
    "LABEL": "Protein source volume",
    "ID": "protein_source_vol",
    "UNIT": "µL",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (2, 3, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
DILUITION_FACTOR = {
    "LABEL": "Dilution factor after incubation",
    "ID": "dilution_factor",
    "UNIT": None,
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (3, 0, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
PROTEIN_SOURCE_INCUBATION = {
    "LABEL": "Protein Source incubation",
    "ID": "protein_source_incubation",
    "UNIT": "%",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 100,
    "POSITION": (3, 1, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
INCUBATION_TIME = {
    "LABEL": "Incubation time",
    "ID": "incubation_time",
    "UNIT": "min",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "MIN": 0,
    "OPTIONS": [],
    "MAX": 10000000,
    "POSITION": (3, 2, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
INCUBATION_TEMPERATURE = {
    "LABEL": "Incubation temperature",
    "ID": "incubation_temperature",
    "UNIT": "°C",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": None,
    "MAX": 10000000,
    "POSITION": (3, 3, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
INCUBATION_TYPE = {
    "LABEL": "Incubation type",
    "ID": "incubation_type",
    "UNIT": None,
    "OPTIONS": ["", "Static", "Dynamic"],
    "VALUE": 0,
    "INPUT_TYPE": "select",
    "MIN": None,
    "MAX": None,
    "POSITION": (4, 0, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
NANOPARTICLES_PROTEIN_RATIO = {
    "LABEL": "Ratio Nanoparticles/Protein Source",
    "ID": "nanoparticles_protein_ratio",
    "UNIT": None,
    "VALUE": 0,
    "INPUT_TYPE": "int",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (4, 1, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
CENTRIFUGE = {
    "LABEL": "Centrifuge",
    "ID": "centrifuge",
    "UNIT": None,
    "VALUE": False,
    "INPUT_TYPE": "boolean",
    "OPTIONS": [],
    "MIN": None,
    "MAX": None,
    "POSITION": (4, 2, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
PELLET = {
    "LABEL": "Pellet",
    "ID": "pellet",
    "UNIT": None,
    "VALUE": False,
    "INPUT_TYPE": "boolean",
    "OPTIONS": [],
    "MIN": None,
    "MAX": None,
    "POSITION": (4, 3, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
SURNATANT = {
    "LABEL": "Surnatant",
    "ID": "surnatant",
    "UNIT": None,
    "VALUE": False,
    "INPUT_TYPE": "boolean",
    "OPTIONS": [],
    "MIN": None,
    "MAX": None,
    "POSITION": (5, 0, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
WASHING = {
    "LABEL": "Washing",
    "UNIT": None,
    "ID": "washing",
    "VALUE": 0,
    "OPTIONS": ["", "1", "2", "3", "NO"],
    "INPUT_TYPE": "select",
    "MIN": None,
    "MAX": None,
    "POSITION": (5, 1, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
LASER_POWER = {
    "LABEL": "Laser power",
    "UNIT": "%",
    "ID": "laser_power",
    "VALUE": 0,
    "INPUT_TYPE": "int",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 100,
    "POSITION": (5, 2, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
THAW_CYCLES = {
    "LABEL": "Number of thaw cycles",
    "UNIT": None,
    "ID": "thaw_cycles",
    "VALUE": 0,
    "INPUT_TYPE": "int",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (5, 3, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
PLASMA_COLOR = {
    "LABEL": "Plasma color",
    "ID": "plasma_color",
    "UNIT": None,
    "VALUE": 0,
    "OPTIONS": ["", "Yellow", "Red"],
    "INPUT_TYPE": "select",
    "MIN": None,
    "MAX": None,
    "POSITION": (6, 0, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": False,
}
AVERAGE_CPS = {
    "LABEL": "Average CPS",
    "UNIT": "CPS",
    "ID": "average_cps",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (6, 1, 1, 1),
    "STRETCH": 3,
    "ENABLED": False,
    "REMOVABLE": False,
    "REQUIRED": True,
}

FPGA_FIRMWARE_TYPE = {
    "LABEL": "FPGA firmware type",
    "UNIT": None,
    "ID": "fpga_firmware_type",
    "VALUE": "",
    "INPUT_TYPE": "text",
    "OPTIONS": [],
    "MIN": None,
    "MAX": None,
    "POSITION": (6, 2, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}

SPA_DETECTOR_TYPE = {
    "LABEL": "SPAD Detector Type",
    "ID": "spa_detector_type",
    "UNIT": None,
    "VALUE": 0,
    "OPTIONS": ["", "Blue", "Red"],
    "INPUT_TYPE": "select",
    "MIN": None,
    "MAX": None,
    "POSITION": (6, 3, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}

CUVETTE_TYPE = {
    "LABEL": "Cuvette type",
    "ID": "cuvette_type",
    "UNIT": None,
    "VALUE": 0,
    "OPTIONS": ["", "UV", "VIS", "UV-VIS"],
    "INPUT_TYPE": "select",
    "MIN": None,
    "MAX": None,
    "POSITION": (7, 0, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}

CUVETTE_HOLDER = {
    "LABEL": "Cuvette holder",
    "ID": "cuvette_holder",
    "UNIT": None,
    "VALUE": 0,
    "OPTIONS": ["", "CVH100", "OceanInsight"],
    "INPUT_TYPE": "select",
    "MIN": None,
    "MAX": None,
    "POSITION": (7, 1, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}

CUVETTE_MATERIAL = {
    "LABEL": "Cuvette material",
    "ID": "cuvette_material",
    "UNIT": None,
    "VALUE": 0,
    "OPTIONS": ["", "Plastic", "Glass", "Quartz"],
    "INPUT_TYPE": "select",
    "MIN": None,
    "MAX": None,
    "POSITION": (7, 2, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
CUVETTE_LENGTH = {
    "LABEL": "Cuvette length",
    "ID": "cuvette_length",
    "UNIT": "mm",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": None,
    "POSITION": (7, 3, 1, 1),
    "STRETCH": 1,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
CUVETTE_WIDTH = {
    "LABEL": "Cuvette width",
    "ID": "cuvette_width",
    "UNIT": "mm",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": None,
    "POSITION": (8, 0, 1, 1),
    "STRETCH": 1,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
CUVETTE_HEIGHT = {
    "LABEL": "Cuvette height",
    "ID": "cuvette_height",
    "UNIT": "mm",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": None,
    "POSITION": (8, 1, 1, 1),
    "STRETCH": 1,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}
LASER_REPETITION_RATE = {
    "LABEL": "Laser repetition rate",
    "ID": "laser_repetition_rate",
    "UNIT": "MHz",
    "VALUE": 0,
    "INPUT_TYPE": "int",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (8, 2, 1, 1),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": True,
}

LASER_CENTRAL_WAVE_LENGTH = {
    "LABEL": "Laser wavelength",
    "ID": "laser_central_wave_length",
    "UNIT": "nm",
    "VALUE": "",
    "INPUT_TYPE": "text",
    "OPTIONS": [],
    "MIN": None,
    "MAX": None,
    "POSITION": (8, 3, 1, 1),
    "STRETCH": 3,
    "ENABLED": False,
    "REMOVABLE": False,
    "REQUIRED": True,
}
EMISSION_FILTER = {
    "LABEL": "Emission filter wavelength",
    "ID": "emission_filter",
    "UNIT": "nm",
    "VALUE": "",
    "INPUT_TYPE": "text",
    "OPTIONS": [],
    "MIN": None,
    "MAX": None,
    "POSITION": (9, 0, 1, 1),
    "STRETCH": 3,
    "ENABLED": False,
    "REMOVABLE": False,
    "REQUIRED": True,
}

CPS_THRESHOLD = {
    "LABEL": "Pile-up Threshold",
    "ID": "cps_threshold",
    "UNIT": "CPS",
    "VALUE": 0,
    "INPUT_TYPE": "int",
    "OPTIONS": [],
    "MIN": 0,
    "MAX": 10000000,
    "POSITION": (9, 1, 1, 1),
    "STRETCH": 3,
    "ENABLED": False,
    "REMOVABLE": False,
    "REQUIRED": True,
}

SBR = {
    "LABEL": "Average SBR",
    "ID": "sbr",
    "UNIT": "㏈",
    "VALUE": 0,
    "INPUT_TYPE": "float",
    "OPTIONS": [],
    "MIN": -10000000,
    "MAX": 10000000,
    "POSITION": (9, 2, 1, 1),
    "STRETCH": 3,
    "ENABLED": False,
    "REMOVABLE": False,
    "REQUIRED": True,
}

NOTES = {
    "LABEL": "Notes",
    "ID": "notes",
    "UNIT": None,
    "VALUE": "",
    "INPUT_TYPE": "textarea",
    "OPTIONS": [],
    "MIN": None,
    "MAX": None,
    "POSITION": (10, 0, 1, 4),
    "STRETCH": 3,
    "ENABLED": True,
    "REMOVABLE": False,
    "REQUIRED": False,
}


LASERBLOOD_METADATA = [
    ID,
    PDAC_HEALTHY,
    WEEKS,
    SETTINGS_SAMPLE_VOL,
    CUVETTE_TOTAL_VOL,
    SOLVENT_TYPE,
    SOLVENT_VOL,
    NANOPARTICLE_TYPE,
    NANOPARTICLE_CONCENTRATION,
    NANOPARTICLE_VOL,
    PROTEIN_SOURCE,
    PROTEIN_SOURCE_VOL,
    DILUITION_FACTOR,
    PROTEIN_SOURCE_INCUBATION,
    INCUBATION_TYPE,
    INCUBATION_TIME,
    INCUBATION_TEMPERATURE,
    NANOPARTICLES_PROTEIN_RATIO,
    CENTRIFUGE,
    PELLET,
    SURNATANT,
    WASHING,
    LASER_POWER,
    THAW_CYCLES,
    PLASMA_COLOR,
    AVERAGE_CPS,
    CUVETTE_TYPE,
    CUVETTE_HOLDER,
    CUVETTE_MATERIAL,
    CUVETTE_LENGTH,
    CUVETTE_WIDTH,
    CUVETTE_HEIGHT,
    LASER_REPETITION_RATE,
    FPGA_FIRMWARE_TYPE,
    LASER_CENTRAL_WAVE_LENGTH,
    EMISSION_FILTER,
    SPA_DETECTOR_TYPE,
    CPS_THRESHOLD,
    SBR,
    NOTES,
]

METADATA_LASERBLOOD_KEY = "laserblood_settings"

NEW_ADDED_LASERBLOOD_INPUTS_KEY = "laserblood_new_added_inputs"
NEW_ADDED_LASERBLOOD_INPUTS_JSON = json.dumps([], indent=4)

LASERBLOOD_METADATA_JSON = json.dumps(LASERBLOOD_METADATA, indent=4)

LASERBLOOD_METADATA_POPUP = "laserblood_metadata_popup"
